Release2.0.6 drill 4
Drill4J/spring-petclinic-microservices pull request #1
Opened 2021-11-24 12:28 UTC by patsevanton

2021-11-24 15:13 UTC, Oksana2020Gavrilova commented on spring-petclinic-vets-service/src/main/java/org/springframework/samples/petclinic/vets/model/Vet.java
>      public Integer getId() {
need to delete

2021-11-24 15:14 UTC, Oksana2020Gavrilova commented on spring-petclinic-vets-service/src/main/java/org/springframework/samples/petclinic/vets/model/Vet.java
>      public void setFirstName(String firstName) {
need to delete

2021-11-24 15:15 UTC, Oksana2020Gavrilova commented on spring-petclinic-vets-service/src/main/java/org/springframework/samples/petclinic/vets/model/Vet.java
>      public String getLastName() {
need to delete

2021-11-24 15:15 UTC, Oksana2020Gavrilova commented on spring-petclinic-vets-service/src/main/java/org/springframework/samples/petclinic/vets/model/Vet.java
>      public void setLastName(String lastName) {
need to delete

2021-11-24 15:18 UTC, Oksana2020Gavrilova requested changes

2021-11-24 15:18 UTC, Oksana2020Gavrilova commented on spring-petclinic-vets-service/src/main/java/org/springframework/samples/petclinic/vets/model/Vet.java
>      protected Set<Specialty> getSpecialtiesInternal() {
need to delete changes

2021-11-24 15:18 UTC, Oksana2020Gavrilova commented on spring-petclinic-vets-service/src/main/java/org/springframework/samples/petclinic/vets/model/Vet.java
>      public List<Specialty> getSpecialties() {
need to delete changes

2021-11-24 15:18 UTC, Oksana2020Gavrilova commented on spring-petclinic-vets-service/src/main/java/org/springframework/samples/petclinic/vets/model/Vet.java
>      public int getNrOfSpecialties() {
need to delete changes

2021-11-24 15:18 UTC, Oksana2020Gavrilova commented on spring-petclinic-vets-service/src/main/java/org/springframework/samples/petclinic/vets/model/Vet.java
>      public void addSpecialty(Specialty specialty) {
need to delete changes

2021-11-25 05:35 UTC, patsevanton commented
Fixed https://github.com/Drill4J/spring-petclinic-microservices/commit/c4418eff6bfd0408c3f074e9cea21029cf204e4e

2021-11-25 05:35 UTC, closed without merging